name: Matrix Configuration

on:
  push:    
  workflow_dispatch:

jobs:
    # deploy-on-ubuntu:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - name: Echo Docker Details
    #         run: echo info

    #       - name: Run Images
    #         run: docker run hello-world
        
    # delpoy-on-windows:
    #     runs-on: windows-latest
    #     steps:
    #       - name: Echo Docker Details
    #         run: docker info
        
    #       - name: Run Images
    #         run: docker run hello-world
    deploy:
        strategy:
          fail-fast: false
          max-parallel: 2
          matrix:
              os: [ubuntu-latest, windows-latest]
              images: [hello-world, alpine]
              exclude:
                - images: alpine
                  os: windows-latest
            #   include:
            #     - images: amd64/alpine
            #       os: ubuntu-20.04
        runs-on: ${{ matrix.os }}
        steps:
          - name: Echo Docker Info
            run: docker info
        
          - name: Run Image on ${{ matrix.os }}
            run: docker run ${{ matrix.images }}

