name: Workflow Filters and Activities
on:
    workflow_dispatch: 
    # schedule:
    #   - cron: "*/59 * * * *"
    push:
        # branches-ignore: 
        #   - feature/*   #feature/add-payment, feature/upload-document
        #   - test/**      #test/ui/index, test/checkout/payment
        branches: 
          - main
          - '!feature/*'  #ignoring pushing to any branch name starting with feature using !
    pull_request:
      # activities
        types:
          - opened
          - closed
        paths-ignore:   #workflow will only run when a pull request that includes a change on file other than README.md
          - README.md 
        branches:       # configures your workflow to only run on pull requests that target specific branches
          - main

jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
      - run: echo this workflow/job/step is expected for event type - ${{ github.event_name }}